name: Unit

on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  php:
    name: "Test Blue Green Deployment"
    runs-on: ubuntu-latest
    env:
      APP_ENV: test
      DATABASE_URL: mysql://root@127.0.0.1:3306/root
      APP_URL: http://localhost:8000
      APP_SECRET: def00000bb5acb32b54ff8ee130270586eec0e878f7337dc7a837acc31d3ff00f93a56b595448b4b29664847dd51991b3314ff65aeeeb761a133b0ec0e070433bff08e48
      OPENSEARCH_URL: 127.0.0.1:9200
      BLUE_GREEN_DEPLOYMENT: 1
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    services:
      elasticsearch:
        image: 'opensearchproject/opensearch:1'
        env:
          discovery.type: single-node
          plugins.security.disabled: 'true'
        ports:
          - "9200:9200"

    steps:
      - name: Checkout previous major version
        uses: actions/checkout@v4
        with:
          ref: '6.5.x'

      - name: Start Default MySQL
        run: |
          sudo mv /var/lib/mysql /var/lib/mysql-old
          sudo mkdir /var/lib/mysql
          sudo mount -t tmpfs tmpfs /var/lib/mysql -o size=1G
          sudo -u mysql mysqld --datadir=/var/lib/mysql --default-time-zone=SYSTEM --initialize-insecure
          sudo systemctl start mysql

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Archives
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: symfony-cli

      - name: Strip cs-fixer in previous major version
        run: rm -rf vendor-bin

      - name: Setup Composer in previous major version
        run: composer update -o

      - name: Start Webserver
        run: symfony server:start -d

      - name: Install Shopware in previous major version
        run: php src/Core/TestBootstrap.php

      - name: Checkout current major version
        uses: actions/checkout@v4
        with:
          ref: 'trunk'

      - name: Strip cs-fixer in current major version
        run: rm -rf vendor-bin

      - name: Update to current major version
        env:
          DATABASE_URL: mysql://root@127.0.0.1:3306/root_test
        run: |
          composer update -o
          bin/console system:update:finish

      - name: Checkout previous major version again
        uses: actions/checkout@v4
        with:
          ref: '6.5.x'

      - name: Strip cs-fixer in previous major version again
        run: rm -rf vendor-bin

      - name: Setup Composer in previous major version again
        run: |
          composer update -o
          bin/console system:generate-jwt-secret

      - name: Run integration tests in previous major version
        run: php -d memory_limit=-1 vendor/bin/phpunit --testsuite "integration" --stop-on-error --stop-on-failure
